(()=>{
'use strict';
const V='202607281730';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=v=>String(v??'').trim().replace(/\s+/g,' ');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const present=v=>v===true||clean(v).length>0;
function ready(fn){if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',fn);else fn()}
function read(){return window.LBSetup?.read?.()||null}
function write(s){return window.LBSetup?.write?.(s)}
function page(){const p=location.pathname;return{index:/\/mein-setup\/(?:index\.html)?$/i.test(p),module:Number((p.match(/modul-(\d+)\.html/i)||[])[1]||0),finance:/finanzuebersicht\.html$/i.test(p),output:/setup-ausgabe\.html$/i.test(p)}}
function fieldText(el){const host=el.closest('.field,.col,.checklist-item,.input-group,.form-group,.section')||el.parentElement;return clean([el.dataset.storageKey,el.dataset.outputLabel,host?.querySelector('label,.label,h2,h3,h4')?.textContent,host?.textContent?.slice(0,500)].filter(Boolean).join(' ')).toLowerCase()}
function canonical(el){const t=fieldText(el);if(/alltagskonto|gehaltskonto|hauptkonto/.test(t))return'alltagskonto';if(/reservekonto|ersatzkonto|zweites konto|backup-konto/.test(t))return'reservekonto';if(/hauptbörse|hauptboerse|wichtigste börse|wichtigste boerse|primäre börse|primaere boerse/.test(t))return'hauptboerse';if(/referenzkonto|ein-.*auszahlungskonto/.test(t))return'referenzkonto';if(/hauptwallet|wichtigste wallet|primäre wallet|primaere wallet/.test(t))return'hauptwallet';if(/reservewallet|ersatzwallet|zweite wallet/.test(t))return'reservewallet';if(/notfallkontakt|vertrauensperson|notfallperson/.test(t))return'notfallkontakt';if(/jahres-review|nächster review|naechster review|review-datum|prüfdatum/.test(t))return'reviewdatum';return''}
function referenceSuggestions(store){const r=store.referenceData||{},active=a=>(a||[]).filter(x=>!x.archived);const banks=active(r.banks),ex=active(r.exchanges),wa=active(r.wallets);const bankText=x=>x?clean([x.label,x.bank].filter(Boolean).join(' – ')):'';const walletText=x=>x?clean([x.label,x.asset,x.network].filter(Boolean).join(' – ')):'';return{
 alltagskonto:bankText(banks.find(x=>/alltag/i.test(x.role||''))||banks[0]),
 reservekonto:bankText(banks.find(x=>/reserve/i.test(x.role||''))),
 referenzkonto:clean(ex.find(x=>x.referenceAccount)?.referenceAccount||''),
 hauptboerse:clean((ex.find(x=>/aktiv/i.test(x.status||''))||ex[0])?.provider||''),
 hauptwallet:walletText(wa.find(x=>/aktiv|beobachtung/i.test(x.status||''))||wa[0]),
 reservewallet:walletText(wa.find(x=>/reserve|langzeit/i.test((x.purpose||'')+' '+(x.label||'')))),
 reviewdatum:clean(store.profile?.profileReview||'')
}}
function syncModuleFields(){const pg=page();if(!pg.module||!window.LBSetup)return;let store=read();if(!store)return;store.sharedData||={};const suggestions=referenceSuggestions(store);const fields=$$('[data-storage-key]');let changed=false;
 fields.forEach(el=>{const key=canonical(el);if(!key)return;el.dataset.sharedKey=key;let shared=store.sharedData[key]?.value;const suggestion=suggestions[key];if(!present(shared)&&present(suggestion)){store.sharedData[key]={value:suggestion,source:'finanzuebersicht',updatedAt:new Date().toISOString()};shared=suggestion;changed=true}
  const current=el.type==='checkbox'?el.checked:el.value;if(!present(current)&&present(shared)){if(el.type==='checkbox')el.checked=shared===true;else el.value=shared;el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));el.dataset.prefilled='true'}
  const saveShared=()=>{const s=read();if(!s)return;s.sharedData||={};const value=el.type==='checkbox'?el.checked:el.value;s.sharedData[key]={value,source:`modul-${pg.module}`,updatedAt:new Date().toISOString()};write(s)};el.addEventListener('input',saveShared);el.addEventListener('change',saveShared)
 });if(changed)write(store);addPrefillNotice(fields)}
function addPrefillNotice(fields){fields.filter(el=>el.dataset.prefilled==='true').forEach(el=>{const host=el.closest('.field,.col,.checklist-item,.input-group,.form-group')||el.parentElement;if(!host||host.querySelector('.setup-prefill-note'))return;const n=document.createElement('div');n.className='setup-prefill-note';n.textContent='Bereits aus deinem bisherigen Setup übernommen. Du kannst den Eintrag hier prüfen oder anpassen.';host.appendChild(n)})}
const LINKS={
 2:{terms:'Passende Ergänzung',items:[['Finanzübersicht','finanzuebersicht.html#banks'],['Bank- und Kontenübersicht','downloads/Mein-souveraenes-Setup_Bank-und-Kontenuebersicht.pdf']]},
 3:{terms:'Passende Ergänzung',items:[['Wallet-Adressbuch','finanzuebersicht.html#wallets'],['Seed-Sicherungsmappe','downloads/Mein-souveraenes-Setup_Seed-Sicherungsmappe.pdf']]},
 5:{terms:'Für diesen Schritt hilfreich',items:[['Wiederherstellungs-Testprotokoll','downloads/Mein-souveraenes-Setup_Wiederherstellungs-Testprotokoll.pdf'],['Notfall-Checkliste','downloads/Mein-souveraenes-Setup_Notfall-Checkliste.pdf']]},
 7:{terms:'Für deinen Abschluss hilfreich',items:[['Jahres-Review','downloads/Mein-souveraenes-Setup_Jahres-Review.pdf'],['Werkzeugkasten','werkzeugkasten.html']]}
};
function addModuleLinks(){const n=page().module,cfg=LINKS[n];if(!cfg||$('.setup-inline-tools'))return;const sections=$$('.section');const target=sections[Math.min(n===2?1:n===3?1:n===5?2:1,Math.max(0,sections.length-1))]||$('.hero');if(!target)return;const p=document.createElement('p');p.className='setup-inline-tools';p.innerHTML=`${esc(cfg.terms)}: `+cfg.items.map(([t,h])=>`<a href="${h}"${h.endsWith('.pdf')?' target="_blank" rel="noopener"':''}>${esc(t)}</a>`).join(' · ');const heading=target.querySelector('h2,h3');(heading||target).insertAdjacentElement(heading?'afterend':'beforeend',p)}
function financeHash(){if(!page().finance)return;const activate=()=>{const id=(location.hash||'#banks').slice(1);const btn=$(`[data-tab="${CSS.escape(id)}"]`);if(btn)btn.click()};activate();window.addEventListener('hashchange',activate)}
function removeInternalLabels(){if(!page().index)return;$$('.phase-label').forEach(x=>x.remove())}
function maskIban(v){const x=clean(v).replace(/\s+/g,'');return x.length>8?x.slice(0,4)+' •••• •••• •••• '+x.slice(-4):x||'–'}
function maskAddress(v){const x=clean(v);return x.length>14?x.slice(0,7)+'…'+x.slice(-6):x||'–'}
function outputFinance(){if(!page().output||!window.LBSetup||$('#referenceOutput'))return;const modules=$('#modules');if(!modules)return;const section=document.createElement('section');section.className='module';section.id='referenceOutput';section.innerHTML='<div class="module-head"><div><h2>Meine offiziellen Finanzangaben</h2><div>Strukturierte Banken, Zahlungswege und öffentliche Wallet-Adressen</div></div><a href="finanzuebersicht.html">Angaben bearbeiten</a></div><div id="referenceOutputBody" class="no-data">Noch keine strukturierten Finanzangaben erfasst.</div>';modules.insertAdjacentElement('beforebegin',section);
 const render=()=>{const s=read(),r=s?.referenceData||{},full=document.body.dataset.view==='full',active=a=>(a||[]).filter(x=>!x.archived),banks=active(r.banks),ex=active(r.exchanges),wa=active(r.wallets),parts=[];const row=(l,v)=>`<div class="entry"><div class="label">${esc(l)}</div><div class="value">${esc(v||'–')}</div></div>`;
  if(banks.length)parts.push('<div class="section"><h3>Banken & Konten</h3>'+banks.map(x=>`<div class="context"><strong>${esc(x.label||x.bank||'Bankkonto')}</strong>${row('Bank',x.bank)}${row('Rolle / Status',(x.role||'–')+' · '+(x.status||'–'))}${row('IBAN',full&&x.showFull?x.iban:maskIban(x.iban))}${row('BIC',x.bic)}${row('Sperrkontakt',x.support)}${row('Zuletzt geprüft',x.verifiedAt)}</div>`).join('')+'</div>');
  if(ex.length)parts.push('<div class="section"><h3>Börsen & Zahlungswege</h3>'+ex.map(x=>`<div class="context"><strong>${esc(x.provider||'Anbieter')}</strong>${row('Rolle / Status',(x.role||'–')+' · '+(x.status||'–'))}${row('Referenzkonto',x.referenceAccount)}${row('2FA / Whitelist',(x.twoFA||'–')+' · '+(x.whitelist||'–'))}${row('Zuletzt geprüft',x.verifiedAt)}</div>`).join('')+'</div>');
  if(wa.length)parts.push('<div class="section"><h3>Wallet-Adressbuch</h3>'+wa.map(x=>`<div class="context"><strong>${esc(x.label||'Wallet')}</strong>${row('Asset / Netzwerk',(x.asset||'–')+' · '+(x.network||'–'))}${row('Öffentliche Adresse',full&&x.showFull?x.address:maskAddress(x.address))}${row('Memo / Tag',x.memo)}${row('Test / Prüfdatum',(x.testDone?'Test durchgeführt':'Test offen')+' · '+(x.verifiedAt||'–'))}</div>`).join('')+'</div>');
  const box=$('#referenceOutputBody');box.className=parts.length?'':'no-data';box.innerHTML=parts.join('')||'Noch keine strukturierten Finanzangaben erfasst.'};render();document.addEventListener('click',e=>{if(['compactBtn','fullBtn'].includes(e.target?.id))setTimeout(render,30)})}
function styles(){if($('#setupPhase4Style'))return;const st=document.createElement('style');st.id='setupPhase4Style';st.textContent='.setup-inline-tools{margin:9px 0 14px!important;font-size:13px!important;color:#64778b!important}.setup-inline-tools a{color:#00878c!important;text-decoration:underline!important;text-decoration-thickness:1.5px!important;text-underline-offset:3px!important;font-weight:850!important}.setup-inline-tools a:nth-of-type(even){color:#b00062!important}.setup-prefill-note{margin-top:7px;padding:8px 10px;border-left:3px solid #00a7ad;background:#eefafa;color:#486173;font-size:12px;line-height:1.45;border-radius:0 9px 9px 0}@media print{.setup-inline-tools,.setup-prefill-note{display:none!important}}';document.head.appendChild(st)}
ready(()=>{styles();removeInternalLabels();financeHash();syncModuleFields();addModuleLinks();outputFinance()});
})();