(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const KEY='fsa_finanzlebensweg_gesamtstand_v4';
const VERSION='4.1';
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'')||'Lebensplan';
const today=()=>new Date().toISOString().slice(0,10);
let restoring=false,saveTimer=0,oldTitle='';
function keyFor(el,i){return el.id?`id:${el.id}`:el.name?`name:${el.name}:${i}`:`idx:${i}`;}
function readControls(){const out={};$$('input,select,textarea').forEach((el,i)=>{if(el.closest('#ownWishModal,#printBook,.backup-panel'))return;out[keyFor(el,i)]={tag:el.tagName,type:el.type||'',value:el.value,checked:!!el.checked,selectedIndex:el.selectedIndex};});return out;}
function isSelected(card){return card.classList.contains('selected')||card.classList.contains('active')||card.getAttribute('aria-pressed')==='true'||!!card.querySelector('input[type="checkbox"]:checked,input[type="radio"]:checked');}
function readCards(){return $$('[data-wish-id],.wish-card,.goal-card,.card').map((el,i)=>({i,selected:isSelected(el)}));}
function snapshot(){const local={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('fsa_')&&k!==KEY)local[k]=localStorage.getItem(k);}return{version:VERSION,savedAt:new Date().toISOString(),controls:readControls(),cards:readCards(),local};}
function save(show=false){if(restoring)return;try{localStorage.setItem(KEY,JSON.stringify(snapshot()));if(show)toast('Gesamter Lebensplan wurde lokal gespeichert.');}catch(e){console.error(e);if(show)toast('Speichern war auf diesem Gerät nicht möglich.',true);}}
function scheduleSave(){clearTimeout(saveTimer);saveTimer=setTimeout(save,180);}
function apply(data){if(!data||!data.controls)throw new Error('Ungültige Sicherungsdatei');restoring=true;const controls=$$('input,select,textarea').filter(el=>!el.closest('#ownWishModal,#printBook,.backup-panel'));controls.forEach((el,i)=>{const d=data.controls[keyFor(el,i)];if(!d)return;if(el.type==='checkbox'||el.type==='radio')el.checked=!!d.checked;else el.value=d.value??'';el.dispatchEvent(new Event('input',{bubbles:true}));el.dispatchEvent(new Event('change',{bubbles:true}));});(data.cards||[]).forEach(c=>{const el=$$('[data-wish-id],.wish-card,.goal-card,.card')[c.i];if(!el)return;el.classList.toggle('selected',!!c.selected);el.classList.toggle('active',!!c.selected);el.setAttribute('aria-pressed',c.selected?'true':'false');});Object.entries(data.local||{}).forEach(([k,v])=>localStorage.setItem(k,v));restoring=false;setTimeout(()=>{save();location.reload();},250);}
function restore(){try{const raw=localStorage.getItem(KEY);if(raw)apply(JSON.parse(raw));}catch(e){console.warn('Wiederherstellung übersprungen',e);restoring=false;}}
function csvEscape(v){const s=String(v??'');return `"${s.replace(/"/g,'""')}"`;}
function exportCSV(){save();const data=JSON.parse(localStorage.getItem(KEY));const rows=[['Typ','Schlüssel','Wert'],['meta','version',data.version],['meta','savedAt',data.savedAt]];Object.entries(data.controls||{}).forEach(([k,v])=>rows.push(['control',k,JSON.stringify(v)]));(data.cards||[]).forEach((v,i)=>rows.push(['card',String(i),JSON.stringify(v)]));Object.entries(data.local||{}).forEach(([k,v])=>rows.push(['localStorage',k,v]));const csv='\uFEFF'+rows.map(r=>r.map(csvEscape).join(';')).join('\r\n');download(new Blob([csv],{type:'text/csv;charset=utf-8'}),fileBase()+'_Sicherung_'+today()+'.csv');toast('CSV-Sicherung wurde erstellt.');}
function parseCSV(text){const rows=[];let row=[],cell='',q=false;for(let i=0;i<text.length;i++){const ch=text[i];if(q){if(ch==='"'&&text[i+1]==='"'){cell+='"';i++;}else if(ch==='"')q=false;else cell+=ch;}else if(ch==='"')q=true;else if(ch===';'){row.push(cell);cell='';}else if(ch==='\n'){row.push(cell.replace(/\r$/,''));rows.push(row);row=[];cell='';}else cell+=ch;}if(cell||row.length){row.push(cell);rows.push(row);}const data={version:'',savedAt:'',controls:{},cards:[],local:{}};rows.slice(1).forEach(r=>{const[t,k,v]=r;if(t==='meta')data[k]=v;else if(t==='control')data.controls[k]=JSON.parse(v);else if(t==='card')data.cards[Number(k)]=JSON.parse(v);else if(t==='localStorage')data.local[k]=v;});return data;}
function importCSV(file){const reader=new FileReader();reader.onload=()=>{try{apply(parseCSV(String(reader.result||'').replace(/^\uFEFF/,'')));}catch(e){console.error(e);toast('Die CSV-Sicherung konnte nicht gelesen werden.',true);}};reader.readAsText(file,'utf-8');}
function fileBase(){const first=$('#firstName')?.value||$('input[name*="vorname" i]')?.value||'Mein';const last=$('#lastName')?.value||$('input[name*="nachname" i]')?.value||'Lebensweg';return 'Mein-finanzieller-Lebensweg_'+slug(first+'-'+last);}
function download(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;document.body.append(a);a.click();setTimeout(()=>{URL.revokeObjectURL(a.href);a.remove();},500);}
function toast(text,error=false){let t=$('#fsaToast');if(!t){t=document.createElement('div');t.id='fsaToast';t.className='fsa-toast';document.body.append(t);}t.textContent=text;t.classList.toggle('error',error);t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600);}
function addPanel(){if($('#backupPanel'))return;const main=$('main');if(!main)return;const sec=document.createElement('section');sec.id='backupPanel';sec.className='backup-panel';sec.innerHTML=`<div><span class="eyebrow">Sicherung und Gerätewechsel</span><h2>Meinen gesamten Lebensplan sichern</h2><p>Alle Eingaben werden automatisch lokal auf diesem Gerät gespeichert. Die CSV-Sicherung überträgt den vollständigen bearbeitbaren Stand auf ein anderes Gerät. Die PDF bewahrt dein Lebenswerk als lesbares persönliches Dokument.</p></div><div class="backup-actions"><button type="button" data-save>Jetzt lokal speichern</button><button type="button" data-export>CSV exportieren</button><label class="backup-import">CSV importieren<input type="file" accept=".csv,text/csv" data-import></label><button type="button" data-pdf>Vollständige PDF erstellen</button><button type="button" class="danger" data-reset>Alle lokalen Daten löschen</button></div><p class="backup-note">Lokale Speicherung bedeutet: Die Daten bleiben auf deinem Gerät und werden nicht an einen Server übertragen.</p>`;main.append(sec);$('[data-save]',sec).onclick=()=>save(true);$('[data-export]',sec).onclick=exportCSV;$('[data-import]',sec).onchange=e=>{if(e.target.files?.[0])importCSV(e.target.files[0]);};$('[data-pdf]',sec).onclick=printFull;$('[data-reset]',sec).onclick=()=>{if(confirm('Wirklich den gesamten lokal gespeicherten Lebensplan löschen?')){Object.keys(localStorage).filter(k=>k.startsWith('fsa_')).forEach(k=>localStorage.removeItem(k));location.reload();}};}
function staticControl(el){const wrap=document.createElement('div');wrap.className='pdf-field-value';let value='';if(el.type==='checkbox'||el.type==='radio')value=el.checked?'Ja':'Nein';else if(el.tagName==='SELECT')value=el.options[el.selectedIndex]?.textContent||el.value;else value=el.value||'—';wrap.textContent=value;return wrap;}
function cleanClone(src){const c=src.cloneNode(true);const originals=$$('input,select,textarea',src);$$('input,select,textarea',c).forEach((el,i)=>el.replaceWith(staticControl(originals[i]||el)));$$('button,.actions,.range,.own-wish-modal,.backup-panel,.chapter-separator,.quote-break,.life-banner,.banner-thoughts',c).forEach(n=>n.remove());$$('details',c).forEach(d=>d.open=true);$$('summary',c).forEach(s=>{s.textContent=s.textContent.replace(/[+−–—]+\s*$/,'').trim();});return c;}
function textOf(card,sel){return card.querySelector(sel)?.textContent?.replace(/\s+/g,' ')?.trim()||'';}
function fieldLabel(el){const lab=el.closest('label');if(lab){const clone=lab.cloneNode(true);$$('input,select,textarea',clone).forEach(n=>n.remove());const t=clone.textContent.replace(/\s+/g,' ').trim();if(t)return t;}return el.getAttribute('aria-label')||el.placeholder||el.name||'Angabe';}
function fieldValue(el){if(el.type==='checkbox'||el.type==='radio')return el.checked?'Ja':'Nein';if(el.tagName==='SELECT')return el.options[el.selectedIndex]?.textContent?.replace(/\s+/g,' ').trim()||el.value;return String(el.value||'').trim();}
function categoryOf(card){let p=card.parentElement;while(p&&p!==document.body){const h=[...p.children].find(n=>/^H[2-4]$/.test(n.tagName));if(h&&h!==card.querySelector('h3,h4'))return h.textContent.replace(/\s+/g,' ').trim();p=p.parentElement;}return card.getAttribute('data-category')||'Lebensziel';}
function selectedWishRows(){const rows=[];$$('[data-wish-id],.wish-card,.goal-card,.card').forEach(card=>{if(!isSelected(card))return;const title=textOf(card,'h3,h4,strong')||'Wunsch';const description=textOf(card,'p,.subtitle,.description');const fields=[];$$('input,select,textarea',card).forEach(el=>{const value=fieldValue(el);if(!value||value==='Nein'||value==='—')return;fields.push({label:fieldLabel(el),value});});rows.push({title,category:categoryOf(card),description,fields});});return rows;}
function section(title,content,cls=''){const s=document.createElement('section');s.className='print-page full-pdf-section '+cls;s.innerHTML=`<p class="print-eyebrow">Mein finanzieller Lebensweg</p><h2>${esc(title)}</h2>`;if(content instanceof Node)s.append(content);else s.insertAdjacentHTML('beforeend',content);return s;}
function titleOf(src){return(src.querySelector(':scope>summary')?.textContent||src.querySelector(':scope>h2')?.textContent||'Abschnitt').replace(/[+−–—]+\s*$/,'').trim();}
function isWishInputSection(title){return /wünsche.*ziele|ziele.*lebensereignisse|wünsche.*lebensereignisse/i.test(title);}
function appendInputSections(book){const main=$('main');if(!main)return;$$(':scope > details',main).forEach(src=>{const title=titleOf(src);if(isWishInputSection(title))return;const body=src.querySelector(':scope>.body')||src;book.append(section(title,cleanClone(body)));});}
function appendSelectedWishes(book){const wishes=selectedWishRows();if(!wishes.length)return;const html=`<p class="pdf-section-intro">Diese Ziele wurden aktiv ausgewählt. Alle Werte entsprechen dem zum Zeitpunkt der Sicherung eingetragenen Stand.</p><div class="pdf-wish-list selected-only">${wishes.map(w=>`<article><div class="pdf-wish-head"><span>${esc(w.category)}</span><h3>${esc(w.title)}</h3>${w.description?`<p>${esc(w.description)}</p>`:''}</div>${w.fields.map(f=>`<div><strong>${esc(f.label)}</strong><span>${esc(f.value)}</span></div>`).join('')}</article>`).join('')}</div>`;book.append(section('Meine ausgewählten Wünsche, Kosten und Prioritäten',html,'pdf-wishes-section'));}
function appendOwnWishes(book){const ownRaw=localStorage.getItem('fsa_finanzlebensweg_eigene_wuensche_v1');try{const own=JSON.parse(ownRaw||'[]');if(!Array.isArray(own)||!own.length)return;book.append(section('Meine eigenen freien Wünsche',`<div class="pdf-wish-list selected-only">${own.map(w=>`<article><div class="pdf-wish-head"><span>${esc(w.category||'Eigener Wunsch')}</span><h3>${esc(w.name||'Eigener Wunsch')}</h3>${w.description?`<p>${esc(w.description)}</p>`:''}</div><div><strong>Zielalter</strong><span>${esc(w.age||'—')}</span></div><div><strong>Kosten</strong><span>${esc(w.amount||'—')} € · ${esc(w.cadence||'')}</span></div><div><strong>Priorität</strong><span>${esc(w.priority||'—')}</span></div></article>`).join('')}</div>`,'pdf-wishes-section'));}catch(e){console.warn(e);}}
function appendResults(book){const result=$('#resultArea');if(result){$$(':scope > details',result).forEach(src=>book.append(section(titleOf(src),cleanClone(src.querySelector(':scope>.body')||src),'pdf-result-section')));}const final=$('#academyFinal');if(final){const clone=cleanClone(final);book.append(section('Die Akademie erklärt meine Auswertung',clone,'pdf-academy-section'));}}
function buildFullBook(){
  $('#printBook')?.remove();
  const book=document.createElement('article');book.id='printBook';book.className='print-book';
  const first=$('#firstName')?.value||$('input[name*="vorname" i]')?.value||'Mein';
  const last=$('#lastName')?.value||$('input[name*="nachname" i]')?.value||'Lebensweg';
  const why=$('#why')?.value||'',vision=$('#vision')?.value||'';
  book.innerHTML=`<section class="print-cover"><img src="./77BC7C55-B63D-4E28-A882-029C4C11E043.png" alt="Lebensweg"><div class="print-cover-copy"><p class="print-eyebrow">Mein vollständiger persönlicher Lebensplan</p><h1>${esc(first)} ${esc(last)}</h1><p>${esc(why)}</p><blockquote>Dein Wunschleben entsteht nicht durch Zufall, sondern durch einen Plan.</blockquote><small>Stand ${new Intl.DateTimeFormat('de-DE').format(new Date())}</small></div></section>`;
  const intro=document.createElement('div');intro.innerHTML=`<p><strong>Mein Warum:</strong> ${esc(why||'—')}</p><p><strong>So möchte ich später leben:</strong> ${esc(vision||'—')}</p><p>Diese Ausgabe sichert alle persönlichen Angaben, aktiv gewählten Wünsche, finanziellen Werte, Modellannahmen, Ergebnisse und Akademie-Erklärungen dieses Lebensplans.</p>`;book.append(section('Meine Lebensgeschichte und mein Ziel',intro,'pdf-intro-section'));
  appendInputSections(book);
  appendSelectedWishes(book);
  appendOwnWishes(book);
  appendResults(book);
  book.append(section('Meine jährliche Aktualisierung',`<p>Lebenspläne verändern sich. Bewahre diese PDF als persönlichen Stand auf und exportiere zusätzlich die CSV-Sicherung, damit du den vollständigen Plan auf einem anderen Gerät weiterbearbeiten kannst.</p><blockquote class="print-quote">Finanzielle Souveränität bedeutet nicht, reich zu sein. Sie bedeutet, Entscheidungen treffen zu können.</blockquote>`,'print-ending'));
  document.body.append(book);
}
function printFull(){save();buildFullBook();oldTitle=document.title;document.title=fileBase()+'_Stand-'+today();document.body.classList.add('printing-ready');setTimeout(()=>window.print(),180);}
function bindPrintButtons(){$$('button,a').filter(el=>/pdf|drucken|speichern/i.test(el.textContent||'')).forEach(el=>{if(el.closest('.backup-panel'))return;el.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();printFull();},true);});}
function init(){addPanel();restore();document.addEventListener('input',scheduleSave,true);document.addEventListener('change',scheduleSave,true);document.addEventListener('click',e=>{if(e.target.closest('[data-wish-id],.wish-card,.goal-card,.card'))scheduleSave();},true);bindPrintButtons();window.addEventListener('beforeprint',()=>{buildFullBook();document.body.classList.add('printing-ready');});window.addEventListener('afterprint',()=>{document.body.classList.remove('printing-ready');$('#printBook')?.remove();if(oldTitle)document.title=oldTitle;});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,450));else setTimeout(init,450);
})();