(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const slug=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9]+/g,'-').replace(/^-|-$/g,'')||'Lebensplan';
const today=()=>new Date().toISOString().slice(0,10);
const text=n=>String(n?.textContent||'').replace(/\s+/g,' ').trim();
function selectedText(el){return el?.tagName==='SELECT'?(el.options[el.selectedIndex]?.textContent||el.value):el?.value||'';}
function byLabel(rx){for(const el of $$('input,select,textarea')){const label=el.closest('label')||document.querySelector(`label[for="${CSS.escape(el.id||'__none__')}"]`);const t=text(label)||el.getAttribute('aria-label')||el.placeholder||'';if(rx.test(t))return selectedText(el);}return'';}
function fieldValue(el){if(!el)return'';if(el.type==='checkbox'||el.type==='radio')return el.checked?'Ja':'Nein';return selectedText(el);}
function fieldLabel(el){const label=el.closest('label')||document.querySelector(`label[for="${CSS.escape(el.id||'__none__')}"]`);if(label){const c=label.cloneNode(true);$$('input,select,textarea',c).forEach(n=>n.remove());const t=text(c);if(t)return t;}return el.getAttribute('aria-label')||el.placeholder||el.name||'Angabe';}
function isWishCard(el){return !!el.querySelector('h3,h4')&&!!el.querySelector('input,select,textarea')&&/Wunsch|Größenordnung|wichtig/i.test(text(el));}
function statusYes(card){for(const s of $$('select',card)){const v=selectedText(s).trim();if(/^ja$/i.test(v))return true;}for(const i of $$('input[type="checkbox"],input[type="radio"]',card))if(i.checked&&/^ja$/i.test(i.value||'Ja'))return true;return card.classList.contains('selected')||card.classList.contains('active')||card.getAttribute('aria-pressed')==='true';}
function category(card){let p=card.parentElement;while(p&&p!==document.body){let prev=card;while(prev){prev=prev.previousElementSibling;if(prev&&/^H[2-4]$/.test(prev.tagName))return text(prev);}card=p;p=p.parentElement;}return'Lebensziel';}
function readWishes(){const seen=new Set(),out=[];for(const card of $$('[data-wish-id],.wish-card,.goal-card,.card')){if(!isWishCard(card)||!statusYes(card))continue;const title=text(card.querySelector('h3,h4,strong'))||'Wunsch';if(seen.has(title))continue;seen.add(title);const desc=text(card.querySelector('h3,h4')?.nextElementSibling||card.querySelector('p'));
const fields=[];for(const el of $$('input,select,textarea',card)){let value=fieldValue(el).trim();if(!value||/^(ja|nein)$/i.test(value))continue;const label=fieldLabel(el);if(/wie wichtig/i.test(label)||/priorit/i.test(label))fields.push({label:'Priorität',value});else if(/alter/i.test(label)||/alter/i.test(el.placeholder||''))fields.push({label:'Geplantes Alter',value});else if(/budget|betrag|kosten/i.test(label+' '+(el.placeholder||'')))fields.push({label:'Geplanter Betrag',value:/€/.test(value)?value:value+' €'});else if(el.tagName==='SELECT')fields.push({label:'Gewählte Modellvariante',value});else fields.push({label,value});}
out.push({title,category:category(card),desc,fields});}
return out;}
function cloneStatic(src){const c=src.cloneNode(true),orig=$$('input,select,textarea',src);$$('input,select,textarea',c).forEach((el,i)=>{const d=document.createElement('div');d.className='pdfv5-value';d.textContent=fieldValue(orig[i]||el)||'—';el.replaceWith(d);});$$('button,.actions,.range,input[type="range"],.backup-panel,.chapter-separator,.quote-break,.life-banner,.banner-thoughts,nav').forEach(()=>{});$$('button,.actions,.range,input[type="range"],.backup-panel,.chapter-separator,.quote-break,.life-banner,.banner-thoughts,nav',c).forEach(n=>n.remove());$$('details',c).forEach(d=>d.open=true);return c;}
function section(title,body,cls=''){const s=document.createElement('section');s.className='pdfv5-page '+cls;s.innerHTML=`<p class="pdfv5-eyebrow">Mein finanzieller Lebensweg</p><h2>${esc(title)}</h2>`;if(body instanceof Node)s.append(body);else s.insertAdjacentHTML('beforeend',body);return s;}
function findBlock(rx){return $$('details,section').find(el=>rx.test(text(el.querySelector(':scope>summary,:scope>h2,:scope>h3'))));}
function kv(title,rows){return section(title,`<div class="pdfv5-kv">${rows.filter(r=>r[1]!==''&&r[1]!=null).map(([a,b])=>`<div><strong>${esc(a)}</strong><span>${esc(b)}</span></div>`).join('')}</div>`);}
function resultSection(rx,title){const src=findBlock(rx);if(!src)return null;const c=cloneStatic(src.querySelector(':scope>.body')||src);$$('*',c).forEach(n=>{n.style.removeProperty('display');n.style.removeProperty('visibility');n.style.removeProperty('opacity');n.style.removeProperty('color');});return section(title,c,'pdfv5-result');}
function buildBook(){
$('#printBook')?.remove();$('#pdfV5Book')?.remove();const book=document.createElement('article');book.id='pdfV5Book';
const first=$('#firstName')?.value||byLabel(/vorname/i)||'Mein';const last=$('#lastName')?.value||byLabel(/nachname/i)||'Lebensweg';const why=$('#why')?.value||byLabel(/mein warum/i)||'';const vision=$('#vision')?.value||byLabel(/wie möchtest du später leben/i)||'';
book.innerHTML=`<section class="pdfv5-cover"><img src="./77BC7C55-B63D-4E28-A882-029C4C11E043.png" alt="Lebensweg"><p class="pdfv5-eyebrow">Mein vollständiger persönlicher Lebensplan</p><h1>${esc(first)} ${esc(last)}</h1><p>${esc(why)}</p><blockquote>Dein Wunschleben entsteht nicht durch Zufall, sondern durch einen Plan.</blockquote><small>Stand ${new Intl.DateTimeFormat('de-DE').format(new Date())}</small></section>`;
book.append(kv('Meine Lebensgeschichte und mein Ziel',[
['Vorname',first],['Nachname',last],['Geburtsdatum',byLabel(/geburtsdatum/i)],['Geplanter Rentenbeginn',byLabel(/rentenbeginn/i)],['Planung bis zum Alter',byLabel(/planung bis/i)],['Mein Warum',why],['So möchte ich später leben',vision]
]));
book.append(kv('Meine heutige finanzielle Realität',[
['Monatliches Nettoeinkommen',byLabel(/nettoeinkommen/i)],['Weitere regelmäßige Einnahmen',byLabel(/weitere.*einnahmen/i)],['Monatliche Lebenshaltungskosten',byLabel(/lebenshaltungskosten/i)],['Miete oder Immobilienrate',byLabel(/miete|immobilienrate/i)],['Laufende Kreditraten',byLabel(/kreditrat/i)],['Sonstige feste Verpflichtungen',byLabel(/feste verpflichtungen/i)],['Aktuelle monatliche Sparrate',byLabel(/sparrate/i)],['Rücklagen',byLabel(/rücklagen/i)],['Bereits vorhandenes Vermögen',byLabel(/vorhandenes vermögen/i)],['Offene Kredite oder Restschulden',byLabel(/restschulden|offene kredite/i)],['Jährliche Einkommensentwicklung',byLabel(/einkommensentwicklung/i)]
]));
book.append(kv('Gesetzliche Rente und Leben im Ruhestand',[
['Beginn des Berufslebens',byLabel(/beginn des berufslebens/i)],['Bisher erworbene gesetzliche Rente',byLabel(/bisher erworbene.*rente/i)],['Hochgerechnete gesetzliche Rente',byLabel(/hochgerechnete.*rente/i)],['Weitere sichere Einnahmen im Alter',byLabel(/weitere sichere einnahmen/i)],['Gewünschter Monatsbedarf im Alter',byLabel(/monatsbedarf im alter/i)],['Modellinflation',byLabel(/modellinflation/i)],['Modellrendite beim Aufbau',byLabel(/modellrendite.*aufbau/i)],['Modellrendite im Ruhestand',byLabel(/modellrendite.*ruhestand/i)],['Arbeitszeit ab 55',byLabel(/arbeitszeit ab 55/i)]
]));
const wishes=readWishes();book.append(section('Meine ausgewählten Wünsche, Kosten und Prioritäten',wishes.length?`<p class="pdfv5-intro">Diese Wünsche sind in der aktuellen Muster- oder persönlichen Version aktiv ausgewählt.</p><div class="pdfv5-wishes">${wishes.map(w=>`<article><span class="pdfv5-cat">${esc(w.category)}</span><h3>${esc(w.title)}</h3>${w.desc?`<p>${esc(w.desc)}</p>`:''}${w.fields.map(f=>`<div><strong>${esc(f.label)}</strong><span>${esc(f.value)}</span></div>`).join('')}</article>`).join('')}</div>`:`<p>In diesem Stand wurden keine aktiven Wünsche erkannt.</p>`));
for(const [rx,title] of [[/mein persönlicher lebensweg/i,'Mein persönlicher Lebensweg'],[/wunschleben und finanzielle realität/i,'Wunschleben und finanzielle Realität'],[/welche stellschrauben/i,'Welche Stellschrauben habe ich?'],[/was bedeutet finanzielle souveränität/i,'Was bedeutet finanzielle Souveränität?']]){const s=resultSection(rx,title);if(s&&text(s).replace(title,'').length>40)book.append(s);}
const academy=findBlock(/akademie erklärt.*auswertung/i);if(academy){const c=cloneStatic(academy);if(text(c).length>80)book.append(section('Die Akademie erklärt meine Auswertung',c,'pdfv5-result'));}
book.append(section('Meine jährliche Aktualisierung','<p>Lebenspläne verändern sich. Bewahre diese PDF als persönlichen Stand auf und exportiere zusätzlich die CSV-Sicherung, damit du den vollständigen Plan auf einem anderen Gerät weiterbearbeiten kannst.</p><blockquote>Finanzielle Souveränität bedeutet nicht, reich zu sein. Sie bedeutet, Entscheidungen treffen zu können.</blockquote>','pdfv5-end'));
document.body.append(book);document.title=`Mein-finanzieller-Lebensweg_${slug(first+'-'+last)}_Stand-${today()}`;
}
const nativePrint=window.print.bind(window);window.print=function(){buildBook();document.body.classList.add('pdfv5-printing');nativePrint();};
window.addEventListener('beforeprint',()=>{buildBook();document.body.classList.add('pdfv5-printing');});
window.addEventListener('afterprint',()=>{document.body.classList.remove('pdfv5-printing');$('#printBook')?.remove();});
})();