(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const STORE='fsa_finanzlebensweg_visual_v1';
const categories=[
 {key:'wohnen',title:'Wohnen',color:'#00a7ad',meaning:'Zum Wohnen gehören nicht nur Kaufpreis oder Miete. Finanzierung, Nebenkosten, Instandhaltung, Rücklagen und die Frage nach schuldenfreiem Wohnen beeinflussen den gesamten Lebensplan.'},
 {key:'familie',title:'Familie',color:'#c6006f',meaning:'Familie verändert laufende Kosten, Wohnbedarf, Mobilität, verfügbare Zeit und häufig auch die beruflichen Möglichkeiten. Die finanzielle Wirkung entsteht über viele Jahre.'},
 {key:'beruf-und-karriere',title:'Beruf und Karriere',color:'#224f70',meaning:'Weiterbildung und berufliche Entwicklung kosten zunächst Zeit und Geld, können aber die Einkommensbasis dauerhaft verändern. Für große Lebensziele ist Einkommen oft die wichtigste Stellschraube.'},
 {key:'mobilitat',title:'Mobilität',color:'#6b7f91',meaning:'Mobilität besteht nicht nur aus dem Kaufpreis. Finanzierung, Versicherung, Energie, Wartung, Reparaturen und spätere Ersatzanschaffungen wirken dauerhaft auf den finanziellen Spielraum.'},
 {key:'freizeit-und-traume',title:'Freizeit und Träume',color:'#d49a21',meaning:'Erlebnisse und Reisen schaffen Lebensqualität. Jährliche Wünsche, einmalige große Reisen und spätere Ruhestandsziele müssen zeitlich getrennt und bewusst finanziert werden.'},
 {key:'personliche-entwicklung',title:'Persönliche Entwicklung',color:'#7b5aa6',meaning:'Persönliche Entwicklung ist nicht nur eine Ausgabe. Wissen, Fähigkeiten und Orientierung können neue Möglichkeiten eröffnen und langfristig auch Einkommen und Entscheidungen verbessern.'},
 {key:'vermogensaufbau',title:'Vermögensaufbau',color:'#16855b',meaning:'Vermögensaufbau beginnt mit einem tragfähigen monatlichen Überschuss, einer Reserve und einer klaren Struktur. Einzelne Anlagen können ein fehlendes Fundament nicht ersetzen.'},
 {key:'gesundheit-und-alter',title:'Gesundheit und Alter',color:'#d05b73',meaning:'Gesundheit, Pflege, barrierearmes Wohnen, Unterstützung und Mobilität werden oft unterschätzt. Frühzeitige Planung schafft später Wahlmöglichkeiten und Selbstbestimmung.'}
];
const norm=s=>String(s||'').replace(/\s+/g,' ').trim();
const num=s=>{const m=String(s||'').replace(/\./g,'').replace(',','.').match(/-?\d+(?:\.\d+)?/);return m?Number(m[0]):0;};
const selected=card=>card.classList.contains('selected')||card.classList.contains('active')||card.getAttribute('aria-pressed')==='true'||!!card.querySelector('input[type="checkbox"]:checked,input[type="radio"]:checked');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function headings(){return categories.map(c=>({c,h:$$('h2,h3,h4').find(h=>norm(h.textContent)===c.title)})).filter(x=>x.h);}
function categoryFor(card){let found=null;for(const x of headings()){if(x.h.compareDocumentPosition(card)&Node.DOCUMENT_POSITION_FOLLOWING)found=x.c;}return found;}
function cardTitle(card){return norm(card.querySelector('h3,h4,strong')?.textContent)||'Wunsch';}
function priority(card){const text=norm([...card.querySelectorAll('select')].map(s=>s.options[s.selectedIndex]?.textContent||s.value).join(' ')).toLowerCase();if(text.includes('herzenswunsch'))return 1;if(text.includes('sehr wichtig'))return .82;if(text.includes('wichtig'))return .62;if(text.includes('eher unwichtig'))return .35;if(text.includes('unwichtig'))return .18;return .5;}
function financialValue(card){const vals=$$('input[type="number"],input[inputmode="numeric"]',card).map(i=>num(i.value)).filter(v=>v>0);const amount=vals.length?vals[vals.length-1]:num([...card.querySelectorAll('select')].map(s=>s.options[s.selectedIndex]?.textContent||'').join(' '));const txt=norm(card.textContent).toLowerCase();if(txt.includes('monatlich'))return amount;if(txt.includes('jährlich')||txt.includes('jahr'))return amount/12;return amount/Math.max(12,36*12);}
function data(){const map=Object.fromEntries(categories.map(c=>[c.key,{...c,count:0,priority:0,monthly:0,titles:[],story:document.querySelector(`[data-life-section-input="${c.key}"]`)?.value||''}]));$$('[data-wish-id],.wish-card,.goal-card').forEach(card=>{if(!selected(card))return;const c=categoryFor(card);if(!c)return;const d=map[c.key];d.count++;d.priority+=priority(card);d.monthly+=financialValue(card);d.titles.push(cardTitle(card));});Object.values(map).forEach(d=>{d.priority=d.count?d.priority/d.count:0;});return Object.values(map);}
function metric(rx){const all=$$('body *').filter(el=>rx.test(norm(el.textContent))&&el.children.length<4);for(const el of all){const box=el.closest('.metric,.result-card,.stat,.card,div');if(!box)continue;const text=norm(box.textContent);const v=num(text.replace(rx,''));if(v||/0\s*%/.test(text))return v;}return 0;}
function wheelSVG(ds,compact=false){const size=compact?420:520,c=size/2,r=compact?125:155,C=2*Math.PI*r,seg=C/8,gap=8,maxM=Math.max(1,...ds.map(d=>d.monthly));let arcs='',labels='';ds.forEach((d,i)=>{const intensity=Math.min(1,.2+d.priority*.45+(d.monthly/maxM)*.25+Math.min(d.count,3)*.08);const sw=compact?28:36;const start=-90+i*45+22.5;const a=start*Math.PI/180;const lx=c+Math.cos(a)*(r+62),ly=c+Math.sin(a)*(r+62);arcs+=`<circle class="life-wheel-segment" data-key="${d.key}" cx="${c}" cy="${c}" r="${r}" fill="none" stroke="${d.color}" stroke-width="${sw}" stroke-linecap="round" stroke-dasharray="${seg-gap} ${C-seg+gap}" stroke-dashoffset="${-i*seg}" opacity="${(.25+intensity*.75).toFixed(2)}"/>`;labels+=`<g class="life-wheel-label" data-key="${d.key}" transform="translate(${lx.toFixed(1)} ${ly.toFixed(1)})"><circle r="${compact?22:26}" fill="#fff" stroke="${d.color}" stroke-width="3"/><text text-anchor="middle" y="-2" font-size="${compact?12:14}" font-weight="800" fill="#132238">${d.count}</text><text text-anchor="middle" y="13" font-size="9" fill="#5f7185">Ziele</text><text text-anchor="middle" y="${compact?43:48}" font-size="${compact?10:12}" font-weight="700" fill="#132238">${esc(d.title)}</text></g>`;});return `<svg class="life-wheel-svg" viewBox="0 0 ${size} ${size}" role="img" aria-label="Lebensrad mit acht Lebensbereichen"><circle cx="${c}" cy="${c}" r="${r}" fill="none" stroke="#e7eef2" stroke-width="${compact?28:36}"/>${arcs}<circle cx="${c}" cy="${c}" r="${compact?82:100}" fill="#132238"/><text x="${c}" y="${c-12}" text-anchor="middle" font-size="${compact?16:20}" font-weight="800" fill="#fff">Mein geplantes</text><text x="${c}" y="${c+13}" text-anchor="middle" font-size="${compact?20:26}" font-weight="800" fill="#7de0dc">Leben</text><text x="${c}" y="${c+38}" text-anchor="middle" font-size="11" fill="#dce8ef">${ds.reduce((a,d)=>a+d.count,0)} aktive Ziele</text>${labels}</svg>`;}
function miniSVG(d){const count=Math.min(1,d.count/4),prio=d.priority,scope=Math.min(1,d.monthly/1500);const bars=[['Ziele',count,d.color],['Bedeutung',prio,'#c6006f'],['Finanzumfang',scope,'#132238']];return `<svg class="chapter-mini-svg" viewBox="0 0 520 130" role="img" aria-label="Grafische Einordnung für ${esc(d.title)}"><rect x="1" y="1" width="518" height="128" rx="18" fill="#f7fafb" stroke="#d9e5ea"/><text x="24" y="30" font-size="14" font-weight="800" fill="#132238">${esc(d.title)} im Lebensplan</text>${bars.map((b,i)=>`<text x="24" y="${58+i*23}" font-size="11" fill="#607286">${b[0]}</text><rect x="130" y="${48+i*23}" width="330" height="12" rx="6" fill="#e4ecef"/><rect class="mini-fill" x="130" y="${48+i*23}" width="${Math.max(6,330*b[1]).toFixed(1)}" height="12" rx="6" fill="${b[2]}"/><text x="474" y="${58+i*23}" text-anchor="end" font-size="11" font-weight="700" fill="#132238">${i===0?d.count:Math.round(b[1]*100)+' %'}</text>`).join('')}</svg>`;}
function bridgeSVG(coverage,free,need){const pct=Math.max(0,Math.min(100,coverage||0)),end=90+7.2*pct;return `<svg class="bridge-svg" viewBox="0 0 900 280" role="img" aria-label="Brücke zwischen Wunschleben und heutiger finanzieller Grundlage"><defs><linearGradient id="bridgeGrad" x1="0" x2="1"><stop offset="0" stop-color="#00a7ad"/><stop offset="1" stop-color="#c6006f"/></linearGradient></defs><rect width="900" height="280" rx="28" fill="#f7fafb"/><circle cx="95" cy="140" r="58" fill="#132238"/><text x="95" y="130" text-anchor="middle" font-size="15" font-weight="800" fill="#fff">HEUTE</text><text x="95" y="154" text-anchor="middle" font-size="20" font-weight="800" fill="#7de0dc">${free.toLocaleString('de-DE')} €</text><circle cx="805" cy="140" r="58" fill="#132238"/><text x="805" y="130" text-anchor="middle" font-size="15" font-weight="800" fill="#fff">WUNSCHLEBEN</text><text x="805" y="154" text-anchor="middle" font-size="20" font-weight="800" fill="#f6b5d5">${coverage||0} %</text><path d="M153 140 C300 55 600 55 747 140" fill="none" stroke="#dfe8ec" stroke-width="30" stroke-linecap="round"/><path class="bridge-progress" d="M153 140 C300 55 600 55 747 140" pathLength="100" fill="none" stroke="url(#bridgeGrad)" stroke-width="30" stroke-linecap="round" stroke-dasharray="${pct} ${100-pct}"/><text x="450" y="213" text-anchor="middle" font-size="16" font-weight="800" fill="#132238">Noch zu entwickelnder monatlicher Spielraum: ${need.toLocaleString('de-DE')} €</text><text x="450" y="240" text-anchor="middle" font-size="13" fill="#607286">Einkommen, Zeit, Prioritäten und Vermögensaufbau bilden gemeinsam die Brücke.</text></svg>`;}
function insertMini(ds){ds.forEach(d=>{const field=document.querySelector(`[data-life-section="${d.key}"]`);if(!field)return;let box=field.querySelector('.chapter-visual');if(!box){box=document.createElement('div');box.className='chapter-visual';field.append(box);}box.innerHTML=miniSVG(d)+`<p><strong>Akademie-Einordnung:</strong> ${esc(d.meaning)}</p>`;});}
function education(ds){const active=ds.filter(d=>d.count);return `<div class="wish-consequence-grid">${active.map(d=>`<article><span style="--accent:${d.color}">${esc(d.title)}</span><h3>${d.count} ausgewählte${d.count===1?'s Ziel':' Ziele'}</h3><p>${esc(d.meaning)}</p><p class="wish-consequence-list"><strong>Im Plan berücksichtigt:</strong> ${esc(d.titles.join(', '))}</p></article>`).join('')}</div>`;}
function ensureResultDetails(ds){const result=$('#resultArea')||$('main');if(!result)return;let details=$('#premiumLifeVisuals');if(!details){details=document.createElement('details');details.id='premiumLifeVisuals';details.open=true;details.className='premium-life-visuals';details.innerHTML='<summary><span>Visualisierung meines Lebensplans</span></summary><div class="body premium-life-body"></div>';if(result.id==='resultArea')result.prepend(details);else result.append(details);}const coverage=metric(/Deckung des Wunschlebens/i),free=metric(/Heute frei verfügbar/i),reserve=metric(/Erforderliche.*Rücklage/i),need=Math.max(0,Math.abs(Math.min(0,free))+Math.max(0,reserve));details.querySelector('.premium-life-body').innerHTML=`<section class="life-wheel-panel"><div><span class="premium-kicker">Mein Lebensrad</span><h2>So verteilen sich meine Wünsche auf mein Leben</h2><p>Das Lebensrad verbindet die acht Lebensbereiche mit den ausgewählten Zielen, ihrer Bedeutung und ihrer finanziellen Größenordnung. Es bewertet nicht den Menschen, sondern macht den persönlichen Plan sichtbar.</p></div>${wheelSVG(ds)}</section><section class="bridge-panel"><span class="premium-kicker">Wunsch und Wirklichkeit verbinden</span><h2>Mein Wunschleben und mein heutiges Fundament</h2>${bridgeSVG(coverage,free,need)}<p class="academy-visual-note"><strong>Akademie-Auswertung:</strong> Die Brücke zeigt nicht, dass Wünsche falsch sind. Sie zeigt, wie weit Einkommen, laufende Kosten, Zeit, Rücklagen und Vermögensaufbau noch entwickelt werden müssen, damit der Lebensplan dauerhaft tragfähig werden kann.</p></section><section class="chapter-summary-panel"><span class="premium-kicker">Die finanziellen Folgen meiner Wünsche</span><h2>Was hinter den ausgewählten Lebenszielen steht</h2>${education(ds)}</section>`;}
function ensureAcademy(ds){const final=$('#academyFinal');if(!final)return;let block=$('#academyLifeWheel');if(!block){block=document.createElement('section');block.id='academyLifeWheel';block.className='academy-life-wheel';final.prepend(block);}const coverage=metric(/Deckung des Wunschlebens/i),free=metric(/Heute frei verfügbar/i),reserve=metric(/Erforderliche.*Rücklage/i),need=Math.max(0,Math.abs(Math.min(0,free))+Math.max(0,reserve));block.innerHTML=`<div class="academy-life-wheel-copy"><span class="premium-kicker">Die Akademie liest deinen Lebensplan als Ganzes</span><h2>Dein Lebensrad zeigt, was dir wirklich wichtig ist</h2><p>Die acht Bereiche werden nicht getrennt voneinander betrachtet. Wohnen verändert Familie und Mobilität, berufliche Entwicklung beeinflusst Einkommen, Gesundheit wirkt auf den Ruhestand und Vermögensaufbau braucht zuerst ein tragfähiges Fundament.</p></div><div class="academy-wheel-layout">${wheelSVG(ds,true)}<div>${bridgeSVG(coverage,free,need)}<p><strong>Die zentrale Einordnung:</strong> Je größer und vielfältiger das Wunschleben ist, desto wichtiger werden Reihenfolge, Einkommensentwicklung, Zeit und ein gesichertes Fundament. Die Akademie empfiehlt nicht, kleiner zu träumen, sondern den Weg zum Ziel belastbar zu planen.</p></div></div>`;}
function persist(ds){const coverage=metric(/Deckung des Wunschlebens/i),state={version:1,updatedAt:new Date().toISOString(),coverage,categories:ds.map(d=>({key:d.key,title:d.title,count:d.count,priority:d.priority,monthly:d.monthly,story:d.story,titles:d.titles}))};localStorage.setItem(STORE,JSON.stringify(state));let hidden=$('#premiumVisualState');if(!hidden){hidden=document.createElement('textarea');hidden.id='premiumVisualState';hidden.name='premium_visual_state';hidden.hidden=true;($('main')||document.body).append(hidden);}hidden.value=JSON.stringify(state);hidden.dispatchEvent(new Event('input',{bubbles:true}));}
let timer=0,working=false;
function update(){if(working)return;working=true;try{const ds=data();insertMini(ds);ensureResultDetails(ds);ensureAcademy(ds);persist(ds);}finally{working=false;}}
function schedule(){clearTimeout(timer);timer=setTimeout(update,240);}
document.addEventListener('input',schedule,true);document.addEventListener('change',schedule,true);document.addEventListener('click',()=>setTimeout(schedule,180),true);
const start=()=>{setTimeout(update,900);setTimeout(update,1800);new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();